---
# 1. Create the namespace for Nexus
apiVersion: v1
kind: Namespace
metadata:
  name: nexus-repository
---
# 2. Define a PersistentVolume (PVs are cluster‑scoped, so no namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonatypestorage
  labels:
    name: sonatypestorage
spec:
  storageClassName: local-path
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nexus-repository"  # Make sure this directory exists on your node
---
# 3. Create a PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonatype-registry-data
  namespace: nexus-repository
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# 4. Create a ConfigMap for custom Nexus configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-custom-config
  namespace: nexus-repository
data:
  nexus.properties: |
    # Set the Docker HTTPS connector port to 5000
    nexus.docker.https.port=5000
---
# 5. Deploy Nexus Repository OSS with an init container to fix permissions and create required directories
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonatype-registry
  namespace: nexus-repository
  labels:
    app: sonatypestorage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonatype-registry
  template:
    metadata:
      labels:
        app: sonatype-registry
    spec:
      # Ensure the container runs as UID 200 and its volume is writable
      securityContext:
        runAsUser: 200
        fsGroup: 200
      # Init container: create directories and fix ownership
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /nexus-data/log /nexus-data/tmp /nexus-data/instances
              chown -R 200:200 /nexus-data
          volumeMounts:
            - name: registry-vol
              mountPath: /nexus-data
      volumes:
        - name: registry-vol
          persistentVolumeClaim:
            claimName: sonatype-registry-data
        - name: nexus-config
          configMap:
            name: nexus-custom-config
            items:
              - key: nexus.properties
                path: nexus.properties
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: ui
            - containerPort: 5000
              name: docker
          volumeMounts:
            - name: registry-vol
              mountPath: /nexus-data
            - name: nexus-config
              mountPath: /nexus-data/etc/nexus.properties
              subPath: nexus.properties
---
# 6. Expose Nexus via a Service that provides two ports
apiVersion: v1
kind: Service
metadata:
  name: sonatype-service
  namespace: nexus-repository
spec:
  selector:
    app: sonatype-registry
  ports:
    - name: ui
      port: 80         # Externally used for the UI (mapped to container port 8081)
      targetPort: 8081
    - name: docker
      port: 5000       # Externally used for the Docker repository (mapped to container port 5000)
      targetPort: 5000
  type: ClusterIP
---
# 7. Issue a TLS certificate for nexus.ricearaul.com using cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-certificate
  namespace: nexus-repository
spec:
  secretName: nexus-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nexus.ricearaul.com
---
# 8. IngressRoute for the Nexus dashboard (UI) via Traefik’s websecure entrypoint (port 443)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nexus-ui-ingressroute
  namespace: nexus-repository
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nexus.ricearaul.com`)
      priority: 10
      services:
        - name: sonatype-service
          port: 80
  tls:
    secretName: nexus-certificate-secret
---
# 9. IngressRoute for the Nexus Docker repository via Traefik’s docker entrypoint (port 5000)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nexus-docker-ingressroute
  namespace: nexus-repository
spec:
  entryPoints:
    - docker
  routes:
    - kind: Rule
      match: Host(`nexus.ricearaul.com`)
      priority: 10
      services:
        - name: sonatype-service
          port: 5000
  tls:
    secretName: nexus-certificate-secret
