---
# 1. Create a dedicated namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nexus-namespace
---
# 2. ConfigMap with custom nexus.properties to set the Docker HTTPS port to 5000
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-custom-config
  namespace: nexus-namespace
data:
  nexus.properties: |
    # Set Docker HTTPS connector port to 5000 for Docker repository access
    nexus.docker.https.port=5000
---
# 3. PersistentVolumeClaim for Nexus data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-pvc
  namespace: nexus-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# 4. Deployment for Nexus Repository OSS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: ui
            - containerPort: 5000
              name: docker
          volumeMounts:
            # Mount persistent storage for Nexus data
            - name: nexus-data
              mountPath: /nexus-data
            # Mount the custom configuration to override nexus.properties
            - name: nexus-config
              mountPath: /nexus-data/etc/nexus.properties
              subPath: nexus.properties
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data-pvc
        - name: nexus-config
          configMap:
            name: nexus-custom-config
            items:
              - key: nexus.properties
                path: nexus.properties
---
# 5. Service exposing both the UI and the Docker connector
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus-namespace
spec:
  selector:
    app: nexus
  ports:
    - name: ui
      port: 80
      targetPort: 8081
    - name: docker
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
# 6. Certificate for TLS (issued by your Cloudflare-based ClusterIssuer)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-certificate
  namespace: nexus-namespace
spec:
  secretName: nexus-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nexus.ricearaul.com
---
# 7. Traefik IngressRoute for the Nexus UI (accessed via https://nexus.ricearaul.com)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nexus-ui-ingressroute
  namespace: nexus-namespace
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nexus.ricearaul.com`)
      priority: 10
      services:
        - name: nexus
          port: 80
  tls:
    secretName: nexus-certificate-secret
---
# 8. Traefik IngressRoute for the Docker repository (accessed via https://nexus.ricearaul.com:5000)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nexus-docker-ingressroute
  namespace: nexus-namespace
spec:
  entryPoints:
    - docker
  routes:
    - kind: Rule
      match: Host(`nexus.ricearaul.com`)
      priority: 10
      services:
        - name: nexus
          port: 5000
  tls:
    secretName: nexus-certificate-secret
