apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: "docmost"
            - name: POSTGRES_USER
              value: "docmost"
            - name: POSTGRES_PASSWORD
              value: "STRONG_DB_PASSWORD"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - port: 5432
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          volumeMounts:
            - mountPath: /data
              name: redis-storage
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost
  template:
    metadata:
      labels:
        app: docmost
    spec:
      containers:
        - name: docmost
          image: docmost/docmost:latest
          env:
            - name: APP_URL
              value: "http://localhost:3000"
            - name: APP_SECRET
              value: "REPLACE_WITH_LONG_SECRET"
            - name: DATABASE_URL
              value: "postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public"
            - name: REDIS_URL
              value: "redis://redis:6379"
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/data/storage
              name: docmost-storage
      volumes:
        - name: docmost-storage
          persistentVolumeClaim:
            claimName: docmost-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docmost
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: docmost
  type: LoadBalancer
