apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-ricearaul-ingressroute-certificate
  namespace: jaeger
spec:
  secretName: jeager-ricearaul-com-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - jaeger.ricearaul.com