apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger-ricearaul-com-ingressroute
  namespace: jaeger
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jaeger.ricearaul.com`)
      priority: 10
      services:
        - name: jaeger-ui-service
          port: 16686
  tls:
    secretName: jaeger-ricearaul-com-certificate-secret