apiVersion: v1
kind: Service
metadata:
  name: docmost
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: {{ .Values.docmost.service.port }}
      targetPort: {{ .Values.docmost.service.targetPort }}
  selector:
    app: docmost 