{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docmost-ingressroute
  namespace: {{ .Values.namespace.name }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.mandatoryHost }}`){{- if .Values.ingress.additionalHosts }}{{- range .Values.ingress.additionalHosts }} || Host(`{{ . }}`){{- end }}{{- end }}
      priority: {{ .Values.ingressRoute.priority }}
      services:
        - name: docmost
          port: {{ .Values.docmost.service.port }}
{{- end }} 