{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docmost-ingressroute
  namespace: {{ .Values.namespace.name }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: Host(`{{ (index .Values.ingress.hosts 0).host }}`)
      priority: {{ .Values.ingressRoute.priority }}
      services:
        - name: docmost
          port: {{ .Values.docmost.service.port }}
  tls:
    secretName: {{ .Values.certificate.secretName }}
{{- end }} 