{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.database.persistence.accessMode }}
  {{- if .Values.database.persistence.storageClass }}
  storageClassName: {{ .Values.database.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
{{- end }}

{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}

{{- if .Values.docmost.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.docmost.persistence.accessMode }}
  {{- if .Values.docmost.persistence.storageClass }}
  storageClassName: {{ .Values.docmost.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.docmost.persistence.size }}
{{- end }} 