{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - mountPath: /data
              name: redis-storage
          {{- end }}
          {{- if .Values.redis.resources }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
      {{- end }}
{{- end }} 