{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
  selector:
    app: redis
{{- end }} 