apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiraworkload-ricearaul-com
  namespace: jiraworkload-ricearaul-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jiraworkload-ricearaul-com
  template:
    metadata:
      labels:
        app: jiraworkload-ricearaul-com
    spec:
      containers:
        - name: jiraworkload-ricearaul-com
          image: k3s.ricearaul.com:5000/jiraworkload.ricearaul.com:latest
          imagePullPolicy: Always
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jiraworkload-ricearaul-ingressroute-certificate
  namespace: jiraworkload-ricearaul-com
spec:
  secretName: jiraworkload-ricearaul-com-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - jiraworkload.ricearaul.com
---
apiVersion: v1
kind: Service
metadata:
  name: jiraworkload-ricearaul-service
  namespace: jiraworkload-ricearaul-com
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: jiraworkload-ricearaul-com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jiraworkload-ricearaul-com-ingressroute
  namespace: jiraworkload-ricearaul-com
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jiraworkload.ricearaul.com`)
      priority: 10
      services:
        - name: jiraworkload-ricearaul-service
          port: 80
  tls:
    secretName: jiraworkload-ricearaul-com-certificate-secret
