apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-agent-cache
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-agent-storage
  resources:
    requests:
      storage: 10Gi