apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-agent-storage
  namespace: jenkins
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain