apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-ricearaul-certificate
  namespace: jenkins
spec:
  secretName: jenkins-ricearaul-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - jenkins.ricearaul.com
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  ports:
    - port: 80
      targetPort: 8080  # Jenkins typically runs on 8080
  selector:
    app.kubernetes.io/component: jenkins-controller  # Standard label for Jenkins helm chart
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ricearaul-ingressroute
  namespace: jenkins
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jenkins.ricearaul.com`)
      priority: 10
      services:
        - name: jenkins-service
          port: 80
  tls:
    secretName: jenkins-ricearaul-certificate-secret