apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-angular-agent
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-angular-agent
  template:
    metadata:
      labels:
        app: jenkins-angular-agent
    spec:
      serviceAccountName: jenkins-agent
      containers:
      - name: jnlp
        image: jenkins/inbound-agent:latest
        env:
          - name: JENKINS_AGENT_NAME
            value: "angular-agent"
          - name: JENKINS_URL
            value: "http://jenkins.jenkins.svc.cluster.local:8080"
          - name: JENKINS_AGENT_WORKDIR
            value: "/home/jenkins"
          - name: JENKINS_SECRET
            valueFrom:
              secretKeyRef:
                name: jenkins-angular-agent-secret
                key: agent-secret
        args:
          - -url
          - "${JENKINS_URL}"
          - -workDir
          - "${JENKINS_AGENT_WORKDIR}"
          - "${JENKINS_SECRET}"
          - "${JENKINS_AGENT_NAME}"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      - name: angular-builder
        image: node:18
        command:
        - /bin/sh
        - -c
        - "while true; do sleep 30; done"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "4Gi"
        volumeMounts:
        - name: npm-cache
          mountPath: /home/jenkins/.npm
      volumes:
      - name: npm-cache
        persistentVolumeClaim:
          claimName: jenkins-agent-cache